SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio, precio * 1.08 AS USD FROM producto;
SELECT nombre AS nombre_producto, precio AS euros, precio * 1.08 AS dolares FROM producto; 
SELECT UPPER(nombre) FROM producto;
SELECT LOWER(nombre) FROM producto;
SELECT nombre, UPPER(LEFT(nombre, 2)) FROM fabricante;
SELECT nombre, ROUND(precio) FROM producto;
SELECT nombre, ROUND(precio, 0) FROM producto;
SELECT codigo_fabricante FROM producto;
SELECT DISTINCT codigo_fabricante FROM producto;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre, precio FROM producto ORDER BY nombre, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 2 offset 3;
SELECT nombre, precio FROM producto ORDER BY precio ASC LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT producto.nombre, codigo_fabricante LIKE 2 FROM producto;
SELECT p.nombre, p.precio, f.nombre FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante;
SELECT p.nombre, p.precio, f.nombre FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante ORDER BY f.nombre ASC;
SELECT p.codigo, p.nombre, f.nombre, f.codigo FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante;
SELECT p.nombre, p.precio, f.nombre FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante ORDER BY p.precio ASC LIMIT 1;
SELECT p.nombre, p.precio, f.nombre FROM producto p INNER JOIN fabricante  f ON f.codigo = p.codigo_fabricante ORDER BY p.precio DESC LIMIT 1;
SELECT p.nombre, f.nombre AS nombre_fabricante FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre = 'Lenovo';
SELECT p.nombre AS nombre_producto, f.nombre AS nombre_fabricante, p.precio FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre = 'Crucial' AND p.precio > 200;
SELECT p.nombre AS nombre_producto, f.nombre AS nombre_fabricante FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE (f.nombre = 'Asus' OR f.nombre = 'Hewlett-Packard' OR f.nombre = 'Seagate');
SELECT p.nombre AS nombre_producto, f.nombre AS nombre_fabricante FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre IN ('Asus', 'Hewlett-Packard', 'Seagate');
SELECT p.nombre AS nombre_producto, p.precio , f.nombre AS nombre_fabricante FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre LIKE '%E';
SELECT p.nombre AS nombre_producto, p.precio, f.nombre AS nombre_fabricante FROM producto p INNER JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre LIKE '%w%';
SELECT p.nombre AS nombre_producto, p.precio, f.nombre AS nombre_fabricante FROM producto p INNER JOIN fabricante  f ON f.codigo = p.codigo_fabricante ORDER BY p.precio >= 180 DESC;
SELECT DISTINCT f.codigo AS fabricante_codigo , f.nombre AS nombre_fabricante FROM fabricante f INNER JOIN producto p ON p.codigo_fabricante = f.codigo WHERE p.codigo IS NULL;
SELECT DISTINCT f.nombre AS nombre_fabricante, p.nombre AS producto_nombre FROM fabricante f LEFT JOIN producto p ON p.codigo_fabricante = f.codigo;
SELECT f.nombre AS nombre_fabricante, p.nombre AS producto_nombre FROM fabricante f LEFT JOIN producto p ON p.codigo_fabricante = f.codigo WHERE p.nombre IS NULL;
SELECT producto.nombre, fabricante.nombre FROM producto, fabricante WHERE producto.codigo_fabricante = fabricante.codigo AND fabricante.nombre = 'Lenovo';
SELECT * FROM producto AS p, fabricante AS f WHERE p.precio IN (SELECT MAX(pr.precio) FROM producto AS pr) AND p.codigo_fabricante = f.codigo AND f.nombre = 'Lenovo';
SELECT p.nombre FROM producto AS p WHERE p.precio IN (SELECT MAX(pr.precio) FROM producto AS pr, fabricante AS f WHERE pr.codigo_fabricante = f.codigo AND f.nombre = 'Lenovo');
SELECT p.nombre FROM producto AS p WHERE p.precio IN (SELECT MIN(pr.precio) FROM producto AS pr, fabricante AS f WHERE pr.codigo_fabricante = f.codigo AND f.nombre = 'Hewlett-Packard');
SELECT p.nombre, p.precio FROM producto p WHERE precio >= (SELECT MAX(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Lenovo'));
SELECT * FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Asus') AND precio > (SELECT AVG(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE nombre = 'Asus'));
